package de.munichhenge.solar

import java.time.Instant

/**
 * Reference values for Munich (48.14° N, 11.58° E), 2026, computed independently with
 * astral 3.x (NOAA algorithm) and cross-checked against pysolar (positions agree within
 * 0.01° in azimuth). Generated by the pipeline venv; see PLAN.md M1.
 */
object MunichReference {
    val MUNICH = GeoPoint(48.14, 11.58)

    /** date, sunrise, noon, sunset (UTC), and the azimuths astral reports at those instants. */
    data class Day(
        val date: String,
        val sunrise: String, val sunriseAz: Double,
        val noon: String, val noonAlt: Double,
        val sunset: String, val sunsetAz: Double,
    )

    val DAYS = listOf(
        Day("2026-03-20", "2026-03-20T05:17:09Z", 89.349, "2026-03-20T11:21:15Z", 41.824, "2026-03-20T17:25:58Z", 270.947),
        Day("2026-06-21", "2026-06-21T03:13:44Z", 52.301, "2026-06-21T11:15:23Z", 65.305, "2026-06-21T19:17:14Z", 307.693),
        Day("2026-09-23", "2026-09-23T05:01:47Z", 89.236, "2026-09-23T11:06:14Z", 41.701, "2026-09-23T17:09:29Z", 270.466),
        Day("2026-12-21", "2026-12-21T07:01:32Z", 125.498, "2026-12-21T11:11:30Z", 18.471, "2026-12-21T15:21:55Z", 234.496),
        Day("2026-01-15", "2026-01-15T06:59:30Z", 121.621, "2026-01-15T11:22:54Z", 20.830, "2026-01-15T15:47:01Z", 238.487),
        Day("2026-04-30", "2026-04-30T03:57:23Z", 66.590, "2026-04-30T11:10:58Z", 56.726, "2026-04-30T18:25:21Z", 293.698),
        Day("2026-08-10", "2026-08-10T04:01:28Z", 65.319, "2026-08-10T11:19:08Z", 57.348, "2026-08-10T18:35:45Z", 294.397),
        Day("2026-10-31", "2026-10-31T05:57:24Z", 110.499, "2026-10-31T10:57:15Z", 27.705, "2026-10-31T15:56:25Z", 249.289),
    )

    /** Arbitrary instants: azimuth and refraction-corrected altitude per astral. */
    data class Pos(val t: String, val az: Double, val alt: Double)

    val POSITIONS = listOf(
        Pos("2026-06-21T12:00:00Z", 203.606, 63.773),
        Pos("2026-06-21T18:30:00Z", 299.075, 5.931),
        Pos("2026-12-21T10:00:00Z", 162.856, 16.690),
        Pos("2026-03-20T06:00:00Z", 97.352, 6.484),
        Pos("2026-09-23T16:45:00Z", 265.906, 3.515),
    )

    fun instant(s: String): Instant = Instant.parse(s)
}
